# Generated by Django 2.1.5 on 2019-01-09 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_lender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='last_borrowed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
