# Generated by Django 2.1.5 on 2019-01-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lender', '0002_auto_20190109_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='img.png', upload_to='static'),
        ),
    ]
