# Generated by Django 2.1.5 on 2019-01-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lender', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='img.png', upload_to='media'),
        ),
    ]
